"""rename filetype to file_type

Revision ID: 1af0a21f26a9
Revises: d409e9a60469
Create Date: 2026-09-11 13:44:21.917105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af0a21f26a9'
down_revision: Union[str, Sequence[str], None] = 'd409e9a60469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(length=100), nullable=False))
    op.drop_column('documents', 'filetype')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filetype', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
