"""add user email tenant constraint

Revision ID: 50ec87894725
Revises: 1bde0ba04aa0
Create Date: 2026-09-11 15:31:29.429651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ec87894725'
down_revision: Union[str, Sequence[str], None] = '1bde0ba04aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_org_email", 'users', ['org_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_org_email", 'users', type_='unique')
    # ### end Alembic commands ###
