"""add document permissions

Revision ID: de5b4792f31b
Revises: 1af0a21f26a9
Create Date: 2026-09-11 13:56:04.320804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5b4792f31b'
down_revision: Union[str, Sequence[str], None] = '1af0a21f26a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documents', ['id', 'org_id'])
    op.create_table('document_permissions',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id', 'org_id'], ['documents.id', 'documents.org_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id', 'org_id'], ['roles.id', 'roles.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_table('document_permissions')
    # ### end Alembic commands ###
